### PR TITLE
74: Add a popup to advertise our logo competition

### LINKED ISSUE #74: Logo Competition Popup
A pop up that appears after 5 seconds asking visitors if they want to go to the competition site [competition.yordevs.com](https://competition.yordevs.com)

### PR DESCRIPTION
**Pull request by benslv**
(closes #74)

I've added a modal thingy which should slide in from the left of the screen after 10 seconds on any of the pages the user is on. They can then close it with a button included in the modal. A couple of questions I have are:

- Is the delay a good length of time, or should it be increased/decreased?
- Do you think having it display on every page a user visits is annoying, and should I implement something which, say, stores when the modal has been closed by the user and no longer displays it from that point onwards?
- Is the messge content good?

### CODE REVIEW

**Comment by benslv** [comment]
Just had a thought, actually, that I'm going to need to add some different behaviour on mobile, because it'll get _really_ annoying for mobile users if it keeps popping up.

**Review by 4dambarr — CHANGES_REQUESTED** [review]
Can we show the modal to the user more than once, my first thought is to do this by storing the time of their visit, then on each page refresh check this and if it is after a set time period (say 10 minutes), show them again.

Also the about page images aren't loading for me on this branch? Can you check this is just to do with my local dependencies and not an issue with the branch as I can't see any reason why this would happen in the files changed

**Comment by benslv** [comment]
> Can we show the modal to the user more than once, my first thought is to do this by storing the time of their visit, then on each page refresh check this and if it is after a set time period (say 10 minutes), show them again.

Yeah, I can add a timestamp to localStorage and get it to check whether a certain amount of time as elasped since then before displaying it again.

> Also the about page images aren't loading for me on this branch? Can you check this is just to do with my local dependencies and not an issue with the branch as I can't see any reason why this would happen in the files changed

I get this issue sometimes, too; the images get stuck on the lowest-resolution thumbnail instead of loading full. Not entirely sure why it happens but it seems to work fine on prod so I kind of turned a blind eye to it.

**Review by 4dambarr — APPROVED** [review]
Approved as requested changes moved to a new issue

**Pull request merged**
